# Generated by Django 5.2.6 on 2025-09-27 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('stock_available', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('customer_rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('demand_forecast', models.PositiveIntegerField()),
                ('optimized_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
