# Generated by Django 5.2.6 on 2025-09-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
