# Generated by Django 5.2.6 on 2025-10-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_products_options_alter_products_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='optimized_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
