# Generated by Django 5.2.6 on 2025-10-02 17:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_products_optimized_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Products.products')),
            ],
            options={
                'verbose_name': 'Product Sale',
                'verbose_name_plural': 'Product Sales',
                'db_table': 'product_sales',
                'ordering': ('date',),
                'unique_together': {('product', 'date')},
            },
        ),
    ]
